# Generated by Django 5.2.8 on 2025-11-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='repondent_department',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='response',
            name='respondent_attachment_period',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='response',
            name='respondent_center',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
