# Generated by Django 5.2.8 on 2025-11-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_response_repondent_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='respondent_attachment_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
