# Generated by Django 5.2.8 on 2025-11-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_response_respondent_attachment_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='repondent_department',
        ),
        migrations.AddField(
            model_name='response',
            name='respondent_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
